const CONTAINER_INNER_HTML = `

    <div class="resultHeaderTable">
      <div class="resultHeaderRow">
        <div class="resultHeaderCell1">攪珠結果</div>
        <div class="resultHeaderCell2"><a href="javascript:PrintResultSinglePage();" style="color:#FFFFFF">列印資料</a></div>
        <div class="resultHeaderCell3"><a href="javascript:PrintResultSinglePage();"><img src="/info/include/images/icon_print.gif?CV=L4.03R2b_CRQ000000131716" title="列印資料" border="0"></a></div>
      </div>
    </div>
    <div id="drawDetails1"><div class="resultSubHeaderRow"><div class="resultDetailsCell1">攪珠期數 : 23/029</div><div class="resultDetailsCell2">攪珠日期 : 16/03/2023(星期四)</div><div class="resultDetailsCell3">總投注額 : $64,058,233</div></div></div>
    <div id="drawDetails2"><div class="resultSubHeaderRow"><div class="resultDetailsCell4">攪珠結果 : </div><div class="resultDetailsCell5"><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_18.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_21.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_28.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_30.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_34.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_40.gif?CV=L4.03R2b_CRQ000000131716"></span><span class="resultDetailsInner" style="padding:0px 5px 0px 5px"><img src="/marksix/info/images/icon_special_no.gif?CV=L4.03R2b_CRQ000000131716" width="6" height="6"></span><span class="resultDetailsInner" style="padding:0px 1px 0px 3px"><img src="/marksix/info/images/icon/no_14.gif?CV=L4.03R2b_CRQ000000131716"></span></div></div></div>
    <div id="resultPrizeTable"><div class="resultPrizeRow"><div class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">頭 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum2">-</span></div><div class="resultPrizeInnerCellRight tableResult2">-</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">二 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$1,553,770</span></div><div class="resultPrizeInnerCellRight tableResult1">2.0</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">三 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$79,680</span></div><div class="resultPrizeInnerCellRight tableResult2">104.0</div></div></div></div><div style="padding:0px 0px 0px 10px;" class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">四 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$9,600</span></div><div class="resultPrizeInnerCellRight tableResult2">191.0</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">五 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$640</span></div><div class="resultPrizeInnerCellRight tableResult1">5,937.1</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">六 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$320</span></div><div class="resultPrizeInnerCellRight tableResult2">6,620.4</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">七 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$40</span></div><div class="resultPrizeInnerCellRight tableResult1">101,840.9</div></div></div></div></div></div>
    <div class="resultFooter">若獲中之獎金為每十元一注超過五百萬元，所有中獎彩票持票人士或經由電話投注服務的中獎人士，包括使用智財咭、1886電話投注自動服務系統等，必須於指定時間致電本會1817登記。﹝使用數碼平台*途徑或香港賽馬會電子錢包除外﹞<br><br>*數碼平台包括網上投注服務「投注區」、馬會投注三合一流動應用程式。</div>

`;
