const CONTAINER_INNER_HTML = `

    <div class="resultHeaderTable">
      <div class="resultHeaderRow">
        <div class="resultHeaderCell1">攪珠結果</div>
        <div class="resultHeaderCell2"><a href="javascript:PrintResultSinglePage();" style="color:#FFFFFF">列印資料</a></div>
        <div class="resultHeaderCell3"><a href="javascript:PrintResultSinglePage();"><img src="/info/include/images/icon_print.gif?CV=L4.06R0c" title="列印資料" border="0"></a></div>
      </div>
    </div>
    <div id="drawDetails1"><div class="resultSubHeaderRow"><div class="resultDetailsCell1">攪珠期數 : 23/139</div><div class="resultDetailsCell2">攪珠日期 : 09/12/2023(星期六)</div><div class="resultDetailsCell3">總投注額 : $64,383,920</div></div></div>
    <div id="drawDetails2"><div class="resultSubHeaderRow"><div class="resultDetailsCell4">攪珠結果 : </div><div class="resultDetailsCell5"><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_02.gif?CV=L4.06R0c"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_03.gif?CV=L4.06R0c"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_04.gif?CV=L4.06R0c"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_31.gif?CV=L4.06R0c"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_46.gif?CV=L4.06R0c"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_49.gif?CV=L4.06R0c"></span><span class="resultDetailsInner" style="padding:0px 5px 0px 5px"><img src="/marksix/info/images/icon_special_no.gif?CV=L4.06R0c" width="6" height="6"></span><span class="resultDetailsInner" style="padding:0px 1px 0px 3px"><img src="/marksix/info/images/icon/no_34.gif?CV=L4.06R0c"></span></div></div></div>
    <div id="resultPrizeTable"><div class="resultPrizeRow"><div class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">頭 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum2">-</span></div><div class="resultPrizeInnerCellRight tableResult2">-</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">二 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$1,253,260</span></div><div class="resultPrizeInnerCellRight tableResult1">2.5</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">三 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$87,480</span></div><div class="resultPrizeInnerCellRight tableResult2">95.5</div></div></div></div><div style="padding:0px 0px 0px 10px;" class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">四 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$9,600</span></div><div class="resultPrizeInnerCellRight tableResult2">197.0</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">五 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$640</span></div><div class="resultPrizeInnerCellRight tableResult1">5,613.2</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">六 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$320</span></div><div class="resultPrizeInnerCellRight tableResult2">6,439.0</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">七 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$40</span></div><div class="resultPrizeInnerCellRight tableResult1">106,742.4</div></div></div></div></div></div>
    <div class="resultFooter"></div>

`;
