const CONTAINER_INNER_HTML = `

    <div class="resultHeaderTable">
      <div class="resultHeaderRow">
        <div class="resultHeaderCell1">攪珠結果</div>
        <div class="resultHeaderCell2"><a href="javascript:PrintResultSinglePage();" style="color:#FFFFFF">列印資料</a></div>
        <div class="resultHeaderCell3"><a href="javascript:PrintResultSinglePage();"><img src="/info/include/images/icon_print.gif?CV=L4.05R2d" title="列印資料" border="0"></a></div>
      </div>
    </div>
    <div id="drawDetails1"><div class="resultSubHeaderRow"><div class="resultDetailsCell1">攪珠期數 : 23/090</div><div class="resultDetailsCell2">攪珠日期 : 12/08/2023(星期六)</div><div class="resultDetailsCell3">總投注額 : $44,887,425</div></div></div>
    <div id="drawDetails2"><div class="resultSubHeaderRow"><div class="resultDetailsCell4">攪珠結果 : </div><div class="resultDetailsCell5"><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_03.gif?CV=L4.05R2d"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_12.gif?CV=L4.05R2d"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_13.gif?CV=L4.05R2d"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_17.gif?CV=L4.05R2d"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_24.gif?CV=L4.05R2d"></span><span class="resultDetailsInner"><img src="/marksix/info/images/icon/no_36.gif?CV=L4.05R2d"></span><span class="resultDetailsInner" style="padding:0px 5px 0px 5px"><img src="/marksix/info/images/icon_special_no.gif?CV=L4.05R2d" width="6" height="6"></span><span class="resultDetailsInner" style="padding:0px 1px 0px 3px"><img src="/marksix/info/images/icon/no_16.gif?CV=L4.05R2d"></span></div></div></div>
    <div id="resultPrizeTable"><div class="resultPrizeRow"><div class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">頭 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum2">-</span></div><div class="resultPrizeInnerCellRight tableResult2">-</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">二 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$952,280</span></div><div class="resultPrizeInnerCellRight tableResult1">2.0</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">三 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$70,530</span></div><div class="resultPrizeInnerCellRight tableResult2">72.0</div></div></div></div><div style="padding:0px 0px 0px 10px;" class="resultPrizeCell"><div class="resultPrizeInnerTable"><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableContentHead"><strong>獎項</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>每注獎金</strong></div><div class="resultPrizeInnerCellRight tableContentHead"><strong>中獎注數</strong></div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">四 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$9,600</span></div><div class="resultPrizeInnerCellRight tableResult2">217.4</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">五 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$640</span></div><div class="resultPrizeInnerCellRight tableResult1">4,736.6</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult2">六 獎</div><div class="resultPrizeInnerCellRight tableResult2"><span class="orangeNum1">$320</span></div><div class="resultPrizeInnerCellRight tableResult2">5,650.9</div></div><div class="resultPrizeInnerRow"><div class="resultPrizeInnerCell tableResult1">七 獎</div><div class="resultPrizeInnerCellRight tableResult1"><span class="orangeNum1">$40</span></div><div class="resultPrizeInnerCellRight tableResult1">83,987.6</div></div></div></div></div></div>
    <div class="resultFooter"></div>

`;
